version: '2'
services:
  user-management.api:
    container_name: user-management.api
    build: .
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - ~/.m2/repository:/user-management-api/repo
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      DB_HOST: kebab.mysql
      DB_NAME: users
      LOGGING_LEVEL_ROOT: warn
      LOGGING_LEVEL_COM_KEBAB: info
      KEBAB_API_VERSION: 1.0.0-SNAPSHOT
      JAVA_OPTS: -Xms128m
                 -Xmx512m
                 -XX:MaxMetaspaceSize=128m
                 -XX:SurvivorRatio=2
                 -XX:+UseConcMarkSweepGC
                 -XX:+CMSParallelRemarkEnabled
                 -XX:+UseCMSInitiatingOccupancyOnly
                 -XX:+ScavengeBeforeFullGC
                 -XX:+CMSScavengeBeforeRemark
                 -Dsun.net.inetaddr.ttl=5
                 -DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector
                 -Djavax.servlet.request.encoding=UTF-8
                 -Dfile.encoding=UTF-8
  event-management.api:
    container_name: event-management.api
    build: ../events-api
    ports:
      - 8081:8080
      - 5006:5005
    volumes:
      - ~/.m2/repository:/event-management-api/repo
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      DB_HOST: kebab.mysql
      DB_NAME: events
      LOGGING_LEVEL_ROOT: warn
      LOGGING_LEVEL_COM_KEBAB: info
      KEBAB_API_VERSION: 1.0.0-SNAPSHOT
      JAVA_OPTS: -Xms128m
                 -Xmx512m
                 -XX:MaxMetaspaceSize=128m
                 -XX:SurvivorRatio=2
                 -XX:+UseConcMarkSweepGC
                 -XX:+CMSParallelRemarkEnabled
                 -XX:+UseCMSInitiatingOccupancyOnly
                 -XX:+ScavengeBeforeFullGC
                 -XX:+CMSScavengeBeforeRemark
                 -Dsun.net.inetaddr.ttl=5
                 -DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector
                 -Djavax.servlet.request.encoding=UTF-8
                 -Dfile.encoding=UTF-8
  kebab-rabbitmq:
    container_name: kebab-rabbitmq
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: kebab
      RABBITMQ_DEFAULT_PASS: kebab
    ports:
      - 15672:15672
      - 5672:5672
    logging:
      driver: none
  kebab.mysql:
    container_name: kebab.mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
    ports:
      - 3307:3306
    logging:
      driver: none